### ISSUE TITLE
Add "Add to slack" submit button

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/slack-secret-santa#5]

**Comment by pyrech** [comment]
https://api.slack.com/slack-apps

**Comment by damienalexandre** [comment]
Our app only use the WebAPI, but the "Add to slack" is designed for apps using either: incoming-webhook bot or commands.

We can't use the "Add to slack" button :cry: even if our app is using oauth and only needs 'chat:write:bot' and 'users:read' rights.
