### ISSUE TITLE
Add support for Discord

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/slack-secret-santa#56]
Provide a new deployment of Slack Secret Santa called "Discord Secret Santa", working with Discord: https://discordapp.com/developers/docs/intro

**Comment by pyrech** [comment]
That's because there is no bot for our Slack app. It's only a webhook, not a real bot

**Comment by pyrech** [comment]
I just checked on Discord, as an admin, I can ban or expulse a bot from the server :wink:
